"""empty message

Revision ID: 40163eed832b
Revises: 8bd96f0a4196
Create Date: 2020-06-29 12:08:57.935986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40163eed832b'
down_revision = '8bd96f0a4196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable= False),
    sa.Column('name', sa.String(), nullable= False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.execute('UPDATE todolists SET todolist_id = 1 WHERE todlist_id is NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'todolist_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
