"""empty message

Revision ID: 8bd96f0a4196
Revises: bb0bb85742e4
Create Date: 2020-06-25 16:34:13.183008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd96f0a4196'
down_revision = 'bb0bb85742e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'notes')
    # ### end Alembic commands ###
