"""empty message

Revision ID: bb0bb85742e4
Revises: adfb6a7188ef
Create Date: 2020-06-25 15:48:28.734004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0bb85742e4'
down_revision = 'adfb6a7188ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=True))
    op.execute('UPDATE todo SET completed = False WHERE completed is NULL')
    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###
